### ISSUE TITLE
Buddy

### ISSUE THREAD

**Issue by MrMC111** [zachrip/valpal#1]
You can equip more then 2 buddys of one type. Also you can equip buddys on knifes.

**Comment by zachrip** [comment]
Fixed the knives issue. Equipping more than 2 buddies of one type is actually allowed by design since you assign buddies to variants and not weapons. I am going to add support for forcing the randomizer to find a skin that has a free to use buddy. I might also make it so if you use a buddy on several skins you can have it randomly choose one in your collection.
